### ISSUE TITLE
http keep-alive

### ISSUE THREAD

**Issue by hunkim** [teampopong/crawlers#36]
HTTP 1.1 부터 나온 keep-alive 옵션은 연결을 끊지않고 여러번의 request가 가능하기 때문에 crawler 의 성능을 서버에 추가 부하를 주지 않고 매우 향샹 시킵니다. Python의 경우 그냥 requests.Session을 만들어 주고 이를 다시 사용하면 자동으로 Keep-alive하거나 연결이 끊어진 경우 다시 연결합니다.

아래 참조:
http://docs.python-requests.org/en/latest/user/advanced/

**Comment by e9t** [comment]
좋은 의견입니다. 기여 감사합니다 :)
